### ISSUE TITLE
Malicious File Detected?

### ISSUE THREAD

**Issue by coppercap** [AJMix/TownOfImpostors#21]
I have downloaded multiple files from this site, but this was the first time i was warned of a 'Malicious File' from my firewall
![malicious01](https://user-images.githubusercontent.com/81863112/113479493-6e664e80-945d-11eb-9d65-df6352b7f390.png)

**Comment by AJMix** [comment]
Yes sometimes depending on your browser settings it will class the .zip as potentially having a malicious file detected. It may be warning for you this time as 1.7.0 is using another version of BepInEx (this is the only big change I can think of, other than changes to my .dll plugin) to be compatible with the latest version of Among Us.

I can guarantee you that there are no malicious files in the .zip

But if you still want to be safe, please feel free to wait until Curseforge finishes reviewing it and you can also download it from Curseforge instead

**Comment by JonyKasual** [comment]
Closing issue.

VirusTotal results of [v1.7.0](https://github.com/AJMix/TownOfImpostors/releases/download/v1.7.0/TownOfImpostors1.7.0.zip) for those who are really concerned [here](https://www.virustotal.com/gui/url/b45fa09e8bf88e6fd940411006cd030d7e9669dd58736d6e4d6a2bc257bf5355/detection).

As @AJMix said, we can guarantee there is no malicious file. This is only Chrome having a small panic attack and asking you to double check the downloaded file because it is a file without many downloads.

The mod can also be downloaded after it has undergone a review at [Curseforge](https://www.curseforge.com/among-us/all-mods/town-of-impostors).
