### ISSUE TITLE
Work With 2021.4.1s pls

### ISSUE THREAD

**Issue by zeldaking** [AJMix/TownOfImpostors#29]
This Is Not A Bug. I Was Just Hoping You Could Add Compatibility For 2021.4.1s On The Next Update.

**Comment by JonyKasual** [comment]
I'll see what @AJMix says, but it is unlikely. Each mod version is released specifically for the stated game version due to the obfuscation unique to each game build. He would not only have to do a lot more work figuring out mappings on two versions, but moreso for a public beta version that is subject to more regular new builds that would break the work done for the build before it.

**Comment by zeldaking** [comment]
nvm I updated my game to the right version.

**Comment by JonyKasual** [comment]
Closing issue in that case.
