### ISSUE TITLE
Missing source folder?

### ISSUE THREAD

**Issue by johnwicksm** [AJMix/TownOfImpostors#3]
The source folder appears to be missing from the github repo. There's only a PICS folder, readme, and license.

**Comment by AJMix** [comment]
The mod is currently not open source.

**Comment by DorCoMaNdO** [comment]
That's not up to you, if you used GPL code, your code is GPL, GPL allows anyone who has access to the software to access the code, and doesn't allow anyone to deny you that right. Add the code or take down the mod.

**Comment by aculver** [comment]
I like chocolate chip pancakes and devs who don't steal code.

**Comment by fladna9** [comment]
Hi.

I'm sorry, but this must be addressed for your own sake @AJMix.

Your project license is GNU/GPLv3, as the LICENSE file says.

This is what GitHub says about GPLv3:
`
Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
`

As section 6 dictates:
```
 6. Conveying Non-Source Forms.

  You may convey a covered work in object code form under the terms
of sections 4 and 5, **provided that you also convey the
machine-readable Corresponding Source under the terms of this License**,
in one of these ways:
[...]
```

Not releasing the source code may be problematic for you, because:

- Not releasing the source code means that NO PART of GNU/GPLv3 is applicable. That is to say, you are liable for any damage done to a user's system.
- Or a court may think otherwise. You may be prosecuted to release the source code in most countries.
- Checking that your code doesn't do **bad things** is important from a cyber-security perspective.
- People **can in fact see most of your source, as C#/dotNet/etc. obfuscation is null** *(ask Innersloth, Unity is using C#/dotNet/Unity as well, and mods are released...)*. A simple tool such as dotPeak can and will not only open your release DLL file, but see mostly all source code inside it. So not releasing it is only making the reading of your code longer, but people definitly can.

I'm sure you're plenty of good intentions, and i don't want you to stop doing what you're doing. Just cover yourself man.
I'm pretty sure your plugin will gain more popularity if you open-source it. People may help you, providing PRs, etc.

Just my two cents.
