### ISSUE TITLE
Loving the new mod

### ISSUE THREAD

**Issue by Hadreshikrar** [AJMix/TownOfImpostors#4]
Hi, 

We are continuing to test this new mod and so far everyone is enjoying the mod though we have possibly encountered another issue although it might just be how the mod works

When Dispose and Disguise are toggled you are unable to use the DNA sample or dispose button as if the buttons are for some reason overlapping preventing them from being used at all, you can use DNA if you don't have dispose turned on and Dispose if you don't have DNA turned on.

We are also wondering if a toggle can be added to turn drag body on and off so that if you don't want the imposter to be able to drag the body it can be turned off.

Another question which isn't so much of an issue, we are currently not using the Doctor as the ability to bring someone back seems a little to over powered as the person is able to almost immediately then vote out the imposter, before finding your mod we were running another mod which had a different version of the doctor which everyone quite enjoyed so we were wondering if it is possible to add a roll similar to this one.

The Medic can give any player a shield that will make them immortal. Although, if The Medic dies, the shield will break. The only exception is The Officer; they will still die if they try to kill a Crewmate. The Medic's other feature shows when they find a corpse: they can get a report that contains clues to the killer's identity. The type of information they get is based on a timer that can be configured inside the lobby.

thanks for all your work

**Comment by AJMix** [comment]
Hi Hadresh,

Thanks again for taking the time to play and test my mod

That's definitely a strange bug you've encountered there, and I have not been able to encounter this myself. All buttons (impostor abilities) should work if they're all toggled on. I'm looking into it now. Could you let me know if this bug where you couldn't use DNA sample/Dispose was happening in all your games? Or was it a one-off?

The ability to toggle drag & drop bodies off will be added in a future update 👍 

Looking into balancing the Doctor, an option will be added where the Doctor will have to drag the body to the map's medbay to revive. This should help balance it by the fact that they could be mistaken for an impostor dragging a body or an impostor could fake the fact that they are dragging a body to medbay. 

But, we do understand the Doctor role can be a little overpowered in the right situations, which is why we encourage the use of a high cooldown for the Revive ability, as well as the Impostor to make use of the Dispose body/Disguise ability to counter it 👍 

Another Guardian role that can shield players can be looked into for a future update, and the ability to get a clue to the killer's identity from reporting a dead body is planned to be added to an upcoming "Detective/Investigator" role!

**Comment by Hadreshikrar** [comment]
Hi AJMix

I think the bug is similar to the new agent roll, for example when we first loaded the agent on Skeld rather than getting two buttons like you are supposed to, the buttons will overlap meaning that you could only see one button, when you try pressing the button it would 95% of the time activate admin but occasionally it would activate the camera?? This issue cleared itself up after one round and didn't happen again.

But when you try to play the impostor with both Disguise and Dispose turned on a similar issue would occur where one of the buttons would hide behind another button, e.g. you are supposed to have 4 buttons, Drag, Dispose, Disguise and DNA but instead you would only have Drag, Disguise and DNA and Dispose would be hidden behind Disguise this would cause the two incorrectly positioned buttons to not work, the only button that never gets effected is Drag which I can only assume is because it is always the first button in the list? I am not sure if this like the agent would clear up if you tried running them multiple games in a row as we were constantly changing the settings to try and see if that would help.

So far this issue would happen every time we tired to run the two ability's together, each ability would work perfectly fine if run by themselves.

That re-balance of the doctor ability definitely sounds like it could work and would add an interesting dynamic, perhaps also adding a small delay before the body is revived as well meaning that if the impostor finds you they have time to kill before the body is fully revived rather than being an instant revive.

Next time we play ill try taking some screenshots when impostor if you haven't figured it out by then :)

**Comment by AJMix** [comment]
Hey!

I've done some refactoring to my button system and since then I haven't run into any button issues during testing, so hopefully these button issues should be cleared up in the next release. But if they continue occurring, please do send screenshots if possible!

The delay before reviving definitely sounds like a good idea & something that can be added! I'll be looking into that

Thanks again for playing and testing the mod :)

**Comment by AJMix** [comment]
Issues mentioned here should be fixed in 1.5 👍
