### ISSUE TITLE
Anonymous votes keeps switching off between rounds

### ISSUE THREAD

**Issue by neomis** [AJMix/TownOfImpostors#5]
Testing out the 1.4 on my Impostor server (thanks for that fix by the way it works great).  The settings reseting has improved greatly but Anonymous votes still resets intermittently.

**Comment by AJMix** [comment]
Hi Neomis! Thanks for playing and testing my mod.

That's really strange, I'll continue looking into it.

There appears to be an issue with the settings sometimes, updating from version to version of this mod, this is likely due to how I'm adding custom settings, which sometimes leads to this issue. **I'll be adding this to known issues.**

What you might want to do is a hard/manual reset on the settings when updating from different versions if you're still having issues with settings resetting. So what you can do is manually set and overwrite each setting (manually toggle each setting on and off, set the timers and set the counts etc.). Every time you change a setting, it ensures it's saved/overwritten in the saved settings.

Or you can open vanilla among us and create a lobby there (this makes it overwrite your saved settings, maybe change a few settings to be sure), then you can open among us with my mod again and this should ensure that all previous (corrupted?) settings have been overwritten/removed.

I'll continue looking into the settings issues, but do let me know if any of the above solutions work.

Thanks

**Comment by AJMix** [comment]
Fixed in 1.5 👍
